// ── MOTIVATIONAL QUOTES ──────────────────────────────────────────────────
export const QUOTES = [
  { text: "Stay hard. The only way through is through.", author: "David Goggins" },
  { text: "You are not your past. You are what you choose to become.", author: "David Goggins" },
  { text: "Suffering is the true test of life.", author: "David Goggins" },
  { text: "Don't stop when you're tired. Stop when you're done.", author: "David Goggins" },
  { text: "Be strong and courageous. Do not be afraid; do not be discouraged.", author: "Joshua 1:9" },
  { text: "I can do all things through Christ who strengthens me.", author: "Philippians 4:13" },
  { text: "The Lord is my strength and my shield.", author: "Psalm 28:7" },
  { text: "Even youths grow tired and weary, but those who hope in the Lord will renew their strength.", author: "Isaiah 40:31" },
  { text: "For God gave us a spirit not of fear but of power and love and self-control.", author: "2 Timothy 1:7" },
  { text: "Champions aren't made in gyms. They're made from something inside them.", author: "Muhammad Ali" },
  { text: "Pain is temporary. Quitting lasts forever.", author: "Lance Armstrong" },
  { text: "Wake up determined. Go to bed satisfied.", author: "Dwayne Johnson" },
  { text: "Hard work beats talent when talent doesn't work hard.", author: "Tim Notke" },
  { text: "If something stands between you and your success, move it. Never be denied.", author: "Dwayne Johnson" },
  { text: "The last three or four reps is what makes the muscle grow.", author: "Arnold Schwarzenegger" },
];

// ── EXERCISE LIBRARY ─────────────────────────────────────────────────────
export const EXERCISE_LIBRARY = {
  Chest: { icon: "💪", exercises: [
    { name: "Barbell Bench Press", type: "Strength", equipment: "Barbell", difficulty: "Intermediate", alternatives: ["Dumbbell Bench Press", "Push-Up", "Machine Chest Press"] },
    { name: "Dumbbell Bench Press", type: "Strength", equipment: "Dumbbells", difficulty: "Beginner", alternatives: ["Barbell Bench Press", "Push-Up", "Cable Fly"] },
    { name: "Incline Bench Press", type: "Strength", equipment: "Barbell", difficulty: "Intermediate", alternatives: ["Incline Dumbbell Press", "Cable Upper Fly", "Smith Machine Incline"] },
    { name: "Push-Up", type: "Bodyweight", equipment: "None", difficulty: "Beginner", alternatives: ["Knee Push-Up", "Wall Push-Up", "Dumbbell Press"] },
    { name: "Cable Fly", type: "Isolation", equipment: "Cable", difficulty: "Beginner", alternatives: ["Dumbbell Fly", "Pec Deck", "Resistance Band Fly"] },
    { name: "Chest Dip", type: "Bodyweight", equipment: "Dip Bar", difficulty: "Intermediate", alternatives: ["Bench Dip", "Machine Dip", "Decline Push-Up"] },
  ]},
  Back: { icon: "🔙", exercises: [
    { name: "Deadlift", type: "Compound", equipment: "Barbell", difficulty: "Advanced", alternatives: ["Romanian Deadlift", "Trap Bar Deadlift", "Dumbbell Deadlift"] },
    { name: "Pull-Up", type: "Bodyweight", equipment: "Pull-Up Bar", difficulty: "Intermediate", alternatives: ["Lat Pulldown", "Assisted Pull-Up", "Resistance Band Pull-Up"] },
    { name: "Barbell Row", type: "Compound", equipment: "Barbell", difficulty: "Intermediate", alternatives: ["Dumbbell Row", "Cable Row", "Machine Row"] },
    { name: "Lat Pulldown", type: "Compound", equipment: "Cable", difficulty: "Beginner", alternatives: ["Pull-Up", "Resistance Band Pulldown", "Dumbbell Pullover"] },
    { name: "Seated Cable Row", type: "Compound", equipment: "Cable", difficulty: "Beginner", alternatives: ["Barbell Row", "Dumbbell Row", "Resistance Band Row"] },
    { name: "Face Pull", type: "Isolation", equipment: "Cable", difficulty: "Beginner", alternatives: ["Rear Delt Fly", "Band Pull Apart", "Dumbbell Rear Delt Fly"] },
  ]},
  Legs: { icon: "🦵", exercises: [
    { name: "Barbell Squat", type: "Compound", equipment: "Barbell", difficulty: "Intermediate", alternatives: ["Goblet Squat", "Leg Press", "Bulgarian Split Squat"] },
    { name: "Romanian Deadlift", type: "Compound", equipment: "Barbell", difficulty: "Intermediate", alternatives: ["Dumbbell RDL", "Cable Pull-Through", "Good Morning"] },
    { name: "Leg Press", type: "Compound", equipment: "Machine", difficulty: "Beginner", alternatives: ["Barbell Squat", "Goblet Squat", "Wall Sit"] },
    { name: "Bulgarian Split Squat", type: "Compound", equipment: "Dumbbells", difficulty: "Intermediate", alternatives: ["Reverse Lunge", "Step-Up", "Single-Leg Leg Press"] },
    { name: "Leg Curl", type: "Isolation", equipment: "Machine", difficulty: "Beginner", alternatives: ["Nordic Curl", "Swiss Ball Curl", "Resistance Band Curl"] },
    { name: "Walking Lunge", type: "Compound", equipment: "Dumbbells", difficulty: "Beginner", alternatives: ["Stationary Lunge", "Reverse Lunge", "Step-Up"] },
    { name: "Calf Raise", type: "Isolation", equipment: "Machine", difficulty: "Beginner", alternatives: ["Seated Calf Raise", "Single-Leg Calf Raise", "Jump Rope"] },
    { name: "Hip Thrust", type: "Compound", equipment: "Barbell", difficulty: "Intermediate", alternatives: ["Glute Bridge", "Cable Kickback", "Resistance Band Hip Thrust"] },
  ]},
  Shoulders: { icon: "🏋️", exercises: [
    { name: "Overhead Press", type: "Compound", equipment: "Barbell", difficulty: "Intermediate", alternatives: ["Dumbbell Shoulder Press", "Arnold Press", "Machine Shoulder Press"] },
    { name: "Dumbbell Shoulder Press", type: "Compound", equipment: "Dumbbells", difficulty: "Beginner", alternatives: ["Barbell OHP", "Arnold Press", "Pike Push-Up"] },
    { name: "Lateral Raise", type: "Isolation", equipment: "Dumbbells", difficulty: "Beginner", alternatives: ["Cable Lateral Raise", "Machine Lateral Raise", "Resistance Band Lateral Raise"] },
    { name: "Arnold Press", type: "Compound", equipment: "Dumbbells", difficulty: "Intermediate", alternatives: ["Dumbbell Press", "Barbell OHP", "Machine Press"] },
    { name: "Rear Delt Fly", type: "Isolation", equipment: "Dumbbells", difficulty: "Beginner", alternatives: ["Cable Rear Delt Fly", "Face Pull", "Band Pull Apart"] },
  ]},
  Arms: { icon: "💪", exercises: [
    { name: "Barbell Curl", type: "Isolation", equipment: "Barbell", difficulty: "Beginner", alternatives: ["Dumbbell Curl", "Cable Curl", "Resistance Band Curl"] },
    { name: "Hammer Curl", type: "Isolation", equipment: "Dumbbells", difficulty: "Beginner", alternatives: ["Rope Curl", "Cross-Body Curl", "Resistance Band Curl"] },
    { name: "Tricep Pushdown", type: "Isolation", equipment: "Cable", difficulty: "Beginner", alternatives: ["Overhead Tricep Extension", "Skull Crusher", "Dip"] },
    { name: "Skull Crusher", type: "Isolation", equipment: "Barbell", difficulty: "Intermediate", alternatives: ["Dumbbell Skull Crusher", "Overhead Extension", "Tricep Pushdown"] },
    { name: "Overhead Tricep Extension", type: "Isolation", equipment: "Dumbbells", difficulty: "Beginner", alternatives: ["Cable Overhead Extension", "Skull Crusher", "Tricep Dip"] },
  ]},
  Core: { icon: "🔥", exercises: [
    { name: "Plank", type: "Isometric", equipment: "None", difficulty: "Beginner", alternatives: ["Dead Bug", "Hollow Hold", "Ab Wheel"] },
    { name: "Hanging Leg Raise", type: "Compound", equipment: "Pull-Up Bar", difficulty: "Intermediate", alternatives: ["Lying Leg Raise", "Captain's Chair", "V-Up"] },
    { name: "Ab Wheel Rollout", type: "Compound", equipment: "Ab Wheel", difficulty: "Intermediate", alternatives: ["TRX Fallout", "Plank", "Dead Bug"] },
    { name: "Russian Twist", type: "Rotation", equipment: "Dumbbells", difficulty: "Beginner", alternatives: ["Cable Wood Chop", "Landmine Rotation", "Med Ball Twist"] },
    { name: "Dead Bug", type: "Stability", equipment: "None", difficulty: "Beginner", alternatives: ["Bird Dog", "Hollow Hold", "Plank"] },
  ]},
  Functional: { icon: "⚡", exercises: [
    { name: "Kettlebell Swing", type: "Power", equipment: "Kettlebell", difficulty: "Intermediate", alternatives: ["Dumbbell Swing", "Cable Pull-Through", "Romanian Deadlift"] },
    { name: "Box Jump", type: "Plyometric", equipment: "Box", difficulty: "Intermediate", alternatives: ["Step-Up", "Jump Squat", "Broad Jump"] },
    { name: "Battle Ropes", type: "Cardio", equipment: "Battle Ropes", difficulty: "Beginner", alternatives: ["Medicine Ball Slam", "Jump Rope", "Rowing Machine"] },
    { name: "TRX Row", type: "Compound", equipment: "TRX", difficulty: "Beginner", alternatives: ["Inverted Row", "Resistance Band Row", "Dumbbell Row"] },
    { name: "Farmer's Carry", type: "Loaded Carry", equipment: "Dumbbells", difficulty: "Beginner", alternatives: ["Suitcase Carry", "Overhead Carry", "Trap Bar Carry"] },
    { name: "Med Ball Slam", type: "Power", equipment: "Medicine Ball", difficulty: "Beginner", alternatives: ["Dumbbell Slam", "Battle Ropes", "Box Jump"] },
    { name: "Burpee", type: "Full Body", equipment: "None", difficulty: "Intermediate", alternatives: ["Half Burpee", "Mountain Climber", "Jump Squat"] },
    { name: "Sandbag Clean", type: "Power", equipment: "Sandbag", difficulty: "Intermediate", alternatives: ["Dumbbell Clean", "Kettlebell Clean", "Barbell Power Clean"] },
    { name: "Sled Push", type: "Loaded Carry", equipment: "Sled", difficulty: "Intermediate", alternatives: ["Car Push", "Prowler Push", "Resistance Band Walk"] },
  ]},
  Cardio: { icon: "🏃", exercises: [
    { name: "Running", type: "Cardio", equipment: "None", difficulty: "Beginner", alternatives: ["Cycling", "Elliptical", "Swimming"] },
    { name: "Jump Rope", type: "Cardio", equipment: "Jump Rope", difficulty: "Beginner", alternatives: ["High Knees", "Box Step", "Battle Ropes"] },
    { name: "Rowing Machine", type: "Cardio", equipment: "Machine", difficulty: "Beginner", alternatives: ["Battle Ropes", "Swimming", "Cycling"] },
    { name: "Cycling", type: "Cardio", equipment: "Bike", difficulty: "Beginner", alternatives: ["Running", "Elliptical", "Rowing"] },
    { name: "Stair Climber", type: "Cardio", equipment: "Machine", difficulty: "Beginner", alternatives: ["Step-Up", "Incline Walk", "Box Jump"] },
  ]},
};

export const ALL_EXERCISES = Object.entries(EXERCISE_LIBRARY).flatMap(([group, data]) =>
  data.exercises.map(ex => ({ ...ex, muscleGroup: group }))
);

// ── PRESET FOODS (per 100g) ──────────────────────────────────────────────
export const PRESET_FOODS = [
  { name: "Chicken Breast", calories: 165, protein: 31, carbs: 0, fat: 4, servingSize: 100, servingUnit: "g" },
  { name: "Ground Beef 93% Lean", calories: 152, protein: 24, carbs: 0, fat: 6, servingSize: 100, servingUnit: "g" },
  { name: "Ground Turkey", calories: 149, protein: 22, carbs: 0, fat: 7, servingSize: 100, servingUnit: "g" },
  { name: "Salmon", calories: 208, protein: 28, carbs: 0, fat: 10, servingSize: 100, servingUnit: "g" },
  { name: "Tuna (canned in water)", calories: 109, protein: 25, carbs: 0, fat: 1, servingSize: 100, servingUnit: "g" },
  { name: "Tilapia", calories: 96, protein: 20, carbs: 0, fat: 2, servingSize: 100, servingUnit: "g" },
  { name: "Shrimp", calories: 99, protein: 24, carbs: 0, fat: 1, servingSize: 100, servingUnit: "g" },
  { name: "Eggs", calories: 155, protein: 13, carbs: 1, fat: 11, servingSize: 100, servingUnit: "g" },
  { name: "Egg Whites", calories: 52, protein: 11, carbs: 1, fat: 0, servingSize: 100, servingUnit: "g" },
  { name: "Bacon", calories: 417, protein: 28, carbs: 1, fat: 33, servingSize: 100, servingUnit: "g" },
  { name: "Pork Tenderloin", calories: 143, protein: 26, carbs: 0, fat: 3, servingSize: 100, servingUnit: "g" },
  { name: "Steak (sirloin)", calories: 207, protein: 26, carbs: 0, fat: 11, servingSize: 100, servingUnit: "g" },
  { name: "Deli Turkey Breast", calories: 84, protein: 17, carbs: 1, fat: 1, servingSize: 100, servingUnit: "g" },
  { name: "Cottage Cheese", calories: 98, protein: 11, carbs: 3, fat: 4, servingSize: 100, servingUnit: "g" },
  { name: "Greek Yogurt (plain)", calories: 59, protein: 10, carbs: 4, fat: 0, servingSize: 100, servingUnit: "g" },
  { name: "Whey Protein Powder", calories: 120, protein: 24, carbs: 3, fat: 2, servingSize: 100, servingUnit: "g" },
  { name: "Whole Milk", calories: 61, protein: 3, carbs: 5, fat: 3, servingSize: 100, servingUnit: "g" },
  { name: "2% Milk", calories: 50, protein: 3, carbs: 5, fat: 2, servingSize: 100, servingUnit: "g" },
  { name: "Cheddar Cheese", calories: 402, protein: 25, carbs: 1, fat: 33, servingSize: 100, servingUnit: "g" },
  { name: "Mozzarella Cheese", calories: 280, protein: 22, carbs: 2, fat: 17, servingSize: 100, servingUnit: "g" },
  { name: "Butter", calories: 717, protein: 1, carbs: 0, fat: 81, servingSize: 100, servingUnit: "g" },
  { name: "White Rice (cooked)", calories: 130, protein: 3, carbs: 28, fat: 0, servingSize: 100, servingUnit: "g" },
  { name: "Brown Rice (cooked)", calories: 112, protein: 3, carbs: 24, fat: 1, servingSize: 100, servingUnit: "g" },
  { name: "Oats (dry)", calories: 389, protein: 17, carbs: 66, fat: 7, servingSize: 100, servingUnit: "g" },
  { name: "White Bread", calories: 265, protein: 9, carbs: 49, fat: 3, servingSize: 100, servingUnit: "g" },
  { name: "Whole Wheat Bread", calories: 247, protein: 13, carbs: 41, fat: 4, servingSize: 100, servingUnit: "g" },
  { name: "Pasta (cooked)", calories: 158, protein: 6, carbs: 31, fat: 1, servingSize: 100, servingUnit: "g" },
  { name: "Flour Tortilla", calories: 312, protein: 8, carbs: 51, fat: 8, servingSize: 100, servingUnit: "g" },
  { name: "Quinoa (cooked)", calories: 120, protein: 4, carbs: 21, fat: 2, servingSize: 100, servingUnit: "g" },
  { name: "White Potato", calories: 77, protein: 2, carbs: 17, fat: 0, servingSize: 100, servingUnit: "g" },
  { name: "Sweet Potato", calories: 86, protein: 2, carbs: 20, fat: 0, servingSize: 100, servingUnit: "g" },
  { name: "Banana", calories: 89, protein: 1, carbs: 23, fat: 0, servingSize: 100, servingUnit: "g" },
  { name: "Apple", calories: 52, protein: 0, carbs: 14, fat: 0, servingSize: 100, servingUnit: "g" },
  { name: "Orange", calories: 47, protein: 1, carbs: 12, fat: 0, servingSize: 100, servingUnit: "g" },
  { name: "Strawberries", calories: 32, protein: 1, carbs: 8, fat: 0, servingSize: 100, servingUnit: "g" },
  { name: "Blueberries", calories: 57, protein: 1, carbs: 14, fat: 0, servingSize: 100, servingUnit: "g" },
  { name: "Mango", calories: 60, protein: 1, carbs: 15, fat: 0, servingSize: 100, servingUnit: "g" },
  { name: "Watermelon", calories: 30, protein: 1, carbs: 8, fat: 0, servingSize: 100, servingUnit: "g" },
  { name: "Pineapple", calories: 50, protein: 1, carbs: 13, fat: 0, servingSize: 100, servingUnit: "g" },
  { name: "Broccoli", calories: 34, protein: 3, carbs: 7, fat: 0, servingSize: 100, servingUnit: "g" },
  { name: "Spinach", calories: 23, protein: 3, carbs: 4, fat: 0, servingSize: 100, servingUnit: "g" },
  { name: "Asparagus", calories: 20, protein: 2, carbs: 4, fat: 0, servingSize: 100, servingUnit: "g" },
  { name: "Green Beans", calories: 31, protein: 2, carbs: 7, fat: 0, servingSize: 100, servingUnit: "g" },
  { name: "Bell Pepper", calories: 31, protein: 1, carbs: 6, fat: 0, servingSize: 100, servingUnit: "g" },
  { name: "Cucumber", calories: 15, protein: 1, carbs: 4, fat: 0, servingSize: 100, servingUnit: "g" },
  { name: "Tomato", calories: 18, protein: 1, carbs: 4, fat: 0, servingSize: 100, servingUnit: "g" },
  { name: "Carrots", calories: 41, protein: 1, carbs: 10, fat: 0, servingSize: 100, servingUnit: "g" },
  { name: "Mushrooms", calories: 22, protein: 3, carbs: 3, fat: 0, servingSize: 100, servingUnit: "g" },
  { name: "Avocado", calories: 160, protein: 2, carbs: 9, fat: 15, servingSize: 100, servingUnit: "g" },
  { name: "Almonds", calories: 579, protein: 21, carbs: 22, fat: 50, servingSize: 100, servingUnit: "g" },
  { name: "Peanut Butter", calories: 588, protein: 25, carbs: 20, fat: 50, servingSize: 100, servingUnit: "g" },
  { name: "Almond Butter", calories: 614, protein: 21, carbs: 19, fat: 56, servingSize: 100, servingUnit: "g" },
  { name: "Olive Oil", calories: 884, protein: 0, carbs: 0, fat: 100, servingSize: 100, servingUnit: "g" },
  { name: "Walnuts", calories: 654, protein: 15, carbs: 14, fat: 65, servingSize: 100, servingUnit: "g" },
  { name: "Cashews", calories: 553, protein: 18, carbs: 30, fat: 44, servingSize: 100, servingUnit: "g" },
  { name: "Black Beans (cooked)", calories: 132, protein: 9, carbs: 24, fat: 1, servingSize: 100, servingUnit: "g" },
  { name: "Chickpeas (cooked)", calories: 164, protein: 9, carbs: 27, fat: 3, servingSize: 100, servingUnit: "g" },
  { name: "Lentils (cooked)", calories: 116, protein: 9, carbs: 20, fat: 0, servingSize: 100, servingUnit: "g" },
  { name: "Quest Protein Bar", calories: 200, protein: 21, carbs: 22, fat: 9, servingSize: 100, servingUnit: "g" },
  { name: "Rice Cakes", calories: 387, protein: 8, carbs: 81, fat: 3, servingSize: 100, servingUnit: "g" },
  { name: "Dark Chocolate 70%", calories: 598, protein: 8, carbs: 46, fat: 43, servingSize: 100, servingUnit: "g" },
  { name: "Hummus", calories: 166, protein: 8, carbs: 14, fat: 10, servingSize: 100, servingUnit: "g" },
  { name: "Chipotle Chicken Bowl", calories: 490, protein: 56, carbs: 22, fat: 18, servingSize: 100, servingUnit: "g" },
];

export const DEFAULT_MACRO_GOALS = { calories: 2040, protein: 180, carbs: 60, fat: 100 };
export const DEFAULT_WEIGHT_GOAL = { current: 0, goal: 0, unit: "lbs", bmr: 0, activityLevel: "moderate" };
